In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
train_df = pd.read_csv('train.txt', sep=';', header=None, names=['text', 'emotion'])
test_df = pd.read_csv('test.txt', sep=';', header=None, names=['text', 'emotion'])

In [3]:
train_df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [4]:
train_df.isnull().sum()

text       0
emotion    0
dtype: int64

In [5]:
train_df.duplicated().sum()

np.int64(1)

In [6]:
train_df.emotion.value_counts()

emotion
joy         5362
sadness     4666
anger       2159
fear        1937
love        1304
surprise     572
Name: count, dtype: int64

In [7]:
unique_emotion = train_df['emotion'].unique()
unique_emotion

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

In [8]:
unique_number = {}
i = 0
for emo in unique_emotion:
  unique_number[emo] = i
  i += 1
train_df['emotion'] = train_df['emotion'].map(unique_number)

In [9]:
train_df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [10]:
train_df.emotion.value_counts()

emotion
5    5362
0    4666
1    2159
4    1937
2    1304
3     572
Name: count, dtype: int64

In [11]:
train_df['text'] = train_df['text'].str.upper() # but we have to convert upper it's just trial because our dataset already lowercase

In [12]:
train_df.head(3)

                                                text  emotion
0                            I DIDNT FEEL HUMILIATED        0
1  I CAN GO FROM FEELING SO HOPELESS TO SO DAMNED...        0
2   IM GRABBING A MINUTE TO POST I FEEL GREEDY WRONG        1

In [13]:
train_df['text'] = train_df['text'].str.lower()

In [14]:
train_df.head(3)

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1

In [15]:
import string

In [16]:
def remove_punc(txt):
  return txt.translate(str.maketrans(' ',' ',string.punctuation))

In [17]:
train_df['text'] = train_df['text'].apply(remove_punc)

In [18]:
train_df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [19]:
def remove_num(txt):
  new = ""
  for i in txt.split():
    if not i.isdigit():
      new += i + " "
  return new
train_df['text'] = train_df['text'].apply(remove_num)

In [20]:
train_df.head()

                                                text  emotion
0                           i didnt feel humiliated         0
1  i can go from feeling so hopeless to so damned...        0
2  im grabbing a minute to post i feel greedy wrong         1
3  i am ever feeling nostalgic about the fireplac...        2
4                              i am feeling grouchy         1

In [53]:
def remove_link(txt):
  new = ""
  for i in txt.split():
    if not i.startswith("http"):
      new += i + " "
  return new
train_df['text'] = train_df['text'].apply(remove_link)

In [22]:
train_df.head()

                                                text  emotion
0                           i didnt feel humiliated         0
1  i can go from feeling so hopeless to so damned...        0
2  im grabbing a minute to post i feel greedy wrong         1
3  i am ever feeling nostalgic about the fireplac...        2
4                              i am feeling grouchy         1

In [23]:
def remove_emoji(txt):
  new = ""
  for i in txt.split():
    if i.isascii():
      new += i + " "
  return new
train_df['text'] = train_df['text'].apply(remove_emoji)

In [24]:
train_df.head()

                                                text  emotion
0                           i didnt feel humiliated         0
1  i can go from feeling so hopeless to so damned...        0
2  im grabbing a minute to post i feel greedy wrong         1
3  i am ever feeling nostalgic about the fireplac...        2
4                              i am feeling grouchy         1

In [25]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('stopwords')
nltk.download('punkt_tab') # it's a library we are using for tokenization

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\manor\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\manor\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [26]:
# after import NLTK will do tokenization
stop_words = set(stopwords.words('english'))

def remove_stopwords(txt):
  word_token = word_tokenize(txt)
  new = ""
  for i in word_token:
    if i not in stop_words:
      new += i + " "
  return new

train_df['text'] = train_df['text'].apply(remove_stopwords)

In [27]:
train_df.head()

                                                text  emotion
0                             didnt feel humiliated         0
1  go feeling hopeless damned hopeful around some...        0
2         im grabbing minute post feel greedy wrong         1
3  ever feeling nostalgic fireplace know still pr...        2
4                                   feeling grouchy         1

In [28]:
train_df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake '

### One Exercise for Bag of words how works

In [29]:
from nltk.corpus.reader import documents
from sklearn.feature_extraction.text import CountVectorizer

documents = ["Manroranjan play football",
             "Sahil also play football",
             "Ranjit play cricket also play football"]

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(documents)

print(vectorizer.get_feature_names_out())
print(X.toarray(), "\n Bag Of Words like this")

['also' 'cricket' 'football' 'manroranjan' 'play' 'ranjit' 'sahil']
[[0 0 1 1 1 0 0]
 [1 0 1 0 1 0 1]
 [1 1 1 0 2 1 0]]
 Bag Of Words like this

## Above function we can call unigram vocabulary because it's created only single single word, so now will use ngram, bigram, trigram, fourgram, etc vocabulary

In [30]:
ngram_vectorizer = CountVectorizer(ngram_range=(1,2)) # this one create n_gram means we can use 1 word of vocabulary and 2 word of vocabulary
X = ngram_vectorizer.fit_transform(documents)
print(ngram_vectorizer.get_feature_names_out())
print(X.toarray())

['also' 'also play' 'cricket' 'cricket also' 'football' 'manroranjan'
 'manroranjan play' 'play' 'play cricket' 'play football' 'ranjit'
 'ranjit play' 'sahil' 'sahil also']
[[0 0 0 0 1 1 1 1 0 1 0 0 0 0]
 [1 1 0 0 1 0 0 1 0 1 0 0 1 1]
 [1 1 1 1 1 0 0 2 1 1 1 1 0 0]]

In [31]:
bigram_vectorizer = CountVectorizer(ngram_range=(2,2)) # we can aslo create bigram vocabulary, two words of vocabulary
X = bigram_vectorizer.fit_transform(documents)
print(bigram_vectorizer.get_feature_names_out())
print(X.toarray())

['also play' 'cricket also' 'manroranjan play' 'play cricket'
 'play football' 'ranjit play' 'sahil also']
[[0 0 1 0 1 0 0]
 [1 0 0 0 1 0 1]
 [1 1 0 1 1 1 0]]

In [32]:
trigram_vecotrizer = CountVectorizer(ngram_range=(3,3)) # we can aslo trigram
X = trigram_vecotrizer.fit_transform(documents)
print(trigram_vecotrizer.get_feature_names_out())
print(X.toarray())

['also play football' 'cricket also play' 'manroranjan play football'
 'play cricket also' 'ranjit play cricket' 'sahil also play']
[[0 0 1 0 0 0]
 [1 0 0 0 0 1]
 [1 1 0 1 1 0]]

In [33]:
fourgram_vecotrizer = CountVectorizer(ngram_range=(4,4)) # we can aslo fourgram
X = fourgram_vecotrizer.fit_transform(documents)
print(fourgram_vecotrizer.get_feature_names_out())
print(X.toarray())

['cricket also play football' 'play cricket also play'
 'ranjit play cricket also' 'sahil also play football']
[[0 0 0 0]
 [0 0 0 1]
 [1 1 1 0]]

# Same kind of things we have use now our project

In [34]:
X = train_df['text']
y = train_df['emotion']

In [35]:
X_vecotrizer = vectorizer.fit_transform(X) # Because we have already created object no need to create again
BOW = X_vecotrizer.toarray()
bow_name_of_list = vectorizer.get_feature_names_out()

In [36]:
len(bow_name_of_list) # We can print every words but it will lot of word so better to understand only how many words used

15042

In [37]:
BOW.shape # also same thing we did here we just checked how many rows and columns used in bag of words matrix

(16000, 15042)

## Now we have to do TF IDF

TF full form of **"Term Frequency"**

IDF full form of **"Inverse of Documents Frequency"**

TF formula is = no. of ocuurance term in document / total no. of terms in documents

IDF fomula is = totla no. of documnets in corpus / no. of document whith term in them

Then calculate `TF x Loge(IDF)`

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer

document = ["Manroranjan play football",
             "Sahil also play football",
             "Ranjit play cricket also play football"]

In [39]:
tf_idf_vectorizer = TfidfVectorizer()

X = tf_idf_vectorizer.fit_transform(document)
print(tf_idf_vectorizer.get_feature_names_out())
print("\n")
print(X.toarray())

['also' 'cricket' 'football' 'manroranjan' 'play' 'ranjit' 'sahil']


[[0.         0.         0.45329466 0.76749457 0.45329466 0.
  0.        ]
 [0.50410689 0.         0.39148397 0.         0.39148397 0.
  0.66283998]
 [0.36580076 0.48098405 0.28407693 0.         0.56815385 0.48098405
  0.        ]]

In [40]:
X.shape

(3, 7)

### Now will do this formula in our project

In [41]:
from sklearn.model_selection import train_test_split

X = train_df['text']
y = train_df['emotion']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [42]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

bow_vectorizer = CountVectorizer()
tf_idf_vectorizer = TfidfVectorizer()

In [43]:
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_train_tf_idf = tf_idf_vectorizer.fit_transform(X_train)


X_test_bow = bow_vectorizer.transform(X_test)
X_test_tf_idf = tf_idf_vectorizer.transform(X_test)

In [44]:
print(X_train_bow.shape)
print(X_train_tf_idf.shape)

(12800, 13357)
(12800, 13357)

In [45]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

nb_bow = MultinomialNB() # using Bag of Word
nb_bow.fit(X_train_bow, y_train)

MultinomialNB()

In [46]:
y_pred_bow = nb_bow.predict(X_test_bow)
print(classification_report(y_test, y_pred_bow))

              precision    recall  f1-score   support

           0       0.75      0.95      0.84       946
           1       0.89      0.64      0.74       427
           2       0.93      0.26      0.41       296
           3       1.00      0.05      0.10       113
           4       0.85      0.57      0.68       397
           5       0.73      0.96      0.83      1021

    accuracy                           0.77      3200
   macro avg       0.86      0.57      0.60      3200
weighted avg       0.80      0.77      0.74      3200

In [47]:
nb_tf = MultinomialNB() # Using TF IDF
nb_tf.fit(X_train_tf_idf, y_train)
y_pred_tf = nb_tf.predict(X_test_tf_idf)
print(classification_report(y_test, y_pred_tf))

              precision    recall  f1-score   support

           0       0.70      0.93      0.80       946
           1       0.93      0.29      0.44       427
           2       1.00      0.03      0.06       296
           3       1.00      0.01      0.02       113
           4       0.92      0.22      0.36       397
           5       0.60      0.99      0.74      1021

    accuracy                           0.66      3200
   macro avg       0.86      0.41      0.40      3200
weighted avg       0.76      0.66      0.58      3200

In [48]:
from sklearn.linear_model import LogisticRegression

lr_tf_idf = LogisticRegression()
lr_tf_idf.fit(X_train_tf_idf, y_train) # using Logistic regression in TF IDF
y_pred_lr_tf = lr_tf_idf.predict(X_test_tf_idf)
print(classification_report(y_test, y_pred_lr_tf))

              precision    recall  f1-score   support

           0       0.90      0.94      0.92       946
           1       0.90      0.81      0.85       427
           2       0.90      0.61      0.73       296
           3       0.88      0.47      0.61       113
           4       0.85      0.76      0.80       397
           5       0.81      0.96      0.88      1021

    accuracy                           0.86      3200
   macro avg       0.87      0.76      0.80      3200
weighted avg       0.87      0.86      0.86      3200

In [49]:
lr_bow = LogisticRegression()
lr_bow.fit(X_train_bow, y_train) # using Logistic regression in BOW
y_pred_lr_bow = lr_bow.predict(X_test_bow)
print(classification_report(y_test, y_pred_lr_bow))

              precision    recall  f1-score   support

           0       0.93      0.93      0.93       946
           1       0.89      0.85      0.87       427
           2       0.84      0.76      0.80       296
           3       0.86      0.73      0.79       113
           4       0.86      0.83      0.85       397
           5       0.88      0.94      0.91      1021

    accuracy                           0.89      3200
   macro avg       0.88      0.84      0.86      3200
weighted avg       0.89      0.89      0.89      3200

In [ ]:
import pickle